### ISSUE TITLE
How do I update the docker file to download the latest version of IB gateway?

### ISSUE THREAD

**Issue by vgoklani** [clifton/docker-ib-gateway#2]
The version built via your docker instance is 950.2i

However the latest version available via the IB website is 955.4k. 

How do I update the docker file to download the latest version?

**Comment by buzzcloudau** [comment]
This pull request will do it - https://github.com/clifton/docker-ib-gateway/pull/3

**Comment by clifton** [comment]
merged @buzzcloudau's update, so we should be good now.
